server:
  port: 1453

logging:
  level:
    root: INFO
    org.wae: DEBUG

spring:
  config:
    activate:
      on-profile: default

  data:
    mongodb:
      host: localhost
      port: 27017
      database: restaurants
      username: root
      password: password
      authentication-database: admin
---
spring:
  application:
    name: halalbites
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: restaurants
      username: root
      password: password
      authentication-database: admin
      uri: mongodb://localhost/test
      repositories.enabled: true

logging:
  level:
    root: INFO
    org.wae.halalbites: DEBUG

---
spring.profiles: docker
server.port: 8080

