server:
  port: 8080

logging:
  level:
    root: INFO
    org.wae: DEBUG

spring:
  config:
    activate:
      on-profile: default

  data:
    mongodb:
      host: localhost
      port: 27017
      database: restaurants
      username: root
      password: password
      authentication-database: admin
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongo
      port: 27017
      database: restaurants
      username: root
      password: password
      authentication-database: admin
      uri: mongodb://localhost/test
      repositories.enabled: true

